### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by somedevreally** [dejablue79/pfsense_VPN_optimizer#10]
am getting this error, last few days. 500 Internal Server Error
```
today at 08:25:24 [2021-07-08 12:25:24,110] ERROR in app: Exception on /set [GET]
today at 08:25:24 Traceback (most recent call last):
today at 08:25:24   File "/venv/lib/python3.7/site-packages/flask/app.py", line 2051, in wsgi_app
today at 08:25:24     response = self.full_dispatch_request()
today at 08:25:24   File "/venv/lib/python3.7/site-packages/flask/app.py", line 1501, in full_dispatch_request
today at 08:25:24     rv = self.handle_user_exception(e)
today at 08:25:24   File "/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in full_dispatch_request
today at 08:25:24     rv = self.dispatch_request()
today at 08:25:24   File "/venv/lib/python3.7/site-packages/flask/app.py", line 1485, in dispatch_request
today at 08:25:24     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
today at 08:25:24   File "./app.py", line 82, in set_pf_clients
today at 08:25:24     return jsonify(set_servers())
today at 08:25:24   File "/app/tasks.py", line 103, in set_servers
today at 08:25:24     data = get_vpn_servers(provider=provider, loc=location)
today at 08:25:24   File "/app/tasks.py", line 22, in get_vpn_servers
today at 08:25:24     data = nordvpn_api.receive_servers_list(loc=loc)
today at 08:25:24   File "/app/modules/nordvpn.py", line 31, in receive_servers_list
today at 08:25:24     resp = r.json()
today at 08:25:24   File "/venv/lib/python3.7/site-packages/requests/models.py", line 900, in json
today at 08:25:24     return complexjson.loads(self.text, **kwargs)
today at 08:25:24   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
today at 08:25:24     return _default_decoder.decode(s)
today at 08:25:24   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
today at 08:25:24     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
today at 08:25:24   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
today at 08:25:24     raise JSONDecodeError("Expecting value", s, err.value) from None
today at 08:25:24 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dejablue79** [comment]
I think its an exception from the pfsense api not responding. (did you upgrade it?)
I will write a handler for it

**Comment by somedevreally** [comment]
right now on pfsense 2.5.2
most of the time it works, ot sure if it started after pfsense update

**Comment by dejablue79** [comment]
You will need to reinstall the API after upgrading.
it removes manually installed stuff.

**Comment by somedevreally** [comment]
FauxAPI? yes have reinstalled.

**Comment by dejablue79** [comment]
is it persistent ?
and if so, can you try and run
`curl "https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations&limit=10"`
?

**Comment by somedevreally** [comment]
no its random, /get works /set have error.
curl works normal, i see the results

**Comment by dejablue79** [comment]
Any chance you could share your Country settings for the VPNs?
maybe i'll be able to reproduce the issue.

**Comment by somedevreally** [comment]
"nordvpn":{"de":{"new":["de788.nordvpn.com"],"old":["de990.nordvpn.com"]},"hu":{"new":["hu56.nordvpn.com"],"old":["hu94.nordvpn.com"]}},"protonvpn":"No Need to Update"}

**Comment by somedevreally** [comment]
after today's update i see this error

`
[1;31mroot@docker [ [0m~[1;31m ]# [0mdocker logs --tail 30 -f nord
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error

`

**Comment by dejablue79** [comment]
Can you try it now?
I split the :latest from my odroid build

**Comment by somedevreally** [comment]
awesome, error is gone.

also can add break between each connection? so its easy to read?
something like this?
```
"nordvpn":
{"ee":{"new":["ee36.nordvpn.com"],"old":["ee192.nordvpn.com"]},
"fi":{"new":["fi142.nordvpn.com"],"old":["fi31.nordvpn.com"]},
"fr":{"new":["fr596.nordvpn.com"],"old":["fr660.nordvpn.com"]},

```

**Comment by somedevreally** [comment]
i also see this,

`{"info":{"error":"('Unable to complete config_set() request', {'callid': '60f439c44faaf', 'action': 'config_set', 'message': 'failed to set new config', 'logs': [{'INFO': '20210718Z102508 :: fauxapi\\\\v1\\\\fauxApi::__call', 'DATA': {'user_action': 'config_set', 'callid': '60f439c44faaf', 'client_ip': 'x.x.x.x'}}, {'ERROR': '20210718Z102508 :: saved config does not match config when saved and reloaded'}]})"},`

**Comment by dejablue79** [comment]
> awesome, error is gone.
> 
> also can add break between each connection? so its easy to read?
> something like this?
> 
> ```
> "nordvpn":
> {"ee":{"new":["ee36.nordvpn.com"],"old":["ee192.nordvpn.com"]},
> "fi":{"new":["fi142.nordvpn.com"],"old":["fi31.nordvpn.com"]},
> "fr":{"new":["fr596.nordvpn.com"],"old":["fr660.nordvpn.com"]},
> ```

if you are using cli, you can try `curl http://xxx.xxx.xxx.xxx:5000/set | jq`

**Comment by somedevreally** [comment]
another error

```
</body>
</html>
[2021-07-18 15:20:01,068] ERROR in app: Exception on /replace/nordvpn [GET]
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./app.py", line 96, in replace
    new=request.args["with"])
  File "/app/tasks.py", line 148, in replace_vpn_location
    return set_servers(renew=new, renew_provider=provider)
  File "/app/tasks.py", line 105, in set_servers
    new_server: dict = next(iter(available_servers[provider][location]))
StopIteration
192.168.1.1 - - [18/Jul/2021 15:20:01] "GET /replace/nordvpn?loc=cz&with=ee HTTP/1.1" 500 -

```

**Comment by somedevreally** [comment]
when  i do /set. its not setting new server name.
`
{"info":{"error":"('Unable to complete config_set() request', {'callid': '60f44c615ceb1', 'action': 'config_set', 'message': 'failed to set new config', 'logs': [{'INFO': '20210718Z114433 :: fauxapi\\\\v1\\\\fauxApi::__call', 'DATA': {'user_action': 'config_set', 'callid': '60f44c615ceb1', 'client_ip': 'x.x.x.x'}}, {'ERROR': '20210718Z114433 :: saved config does not match config when saved and reloaded'}]})"},"nordvpn":{"ee":{"new":["ee36.nordvpn.com"],"old":["ee192.nordvpn.com"]},`

it was supposed to change ee192 to ee36. but its still ee192.
