### ISSUE TITLE
StopIteration error

### ISSUE THREAD

**Issue by somedevreally** [dejablue79/pfsense_VPN_optimizer#2]
when i try to set new server using the link
http://localhost:5000/set i get this error.
sometimes it works, sometimes it gives error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app.py", line 71, in set
    return jsonify(set_servers())
  File "/usr/src/app/tasks.py", line 112, in set_servers
    server = next(iter(sorted_ndata))
StopIteration
```

**Comment by somedevreally** [comment]
also this, just blank. doesn't change the server
```
{
  "NordVPN": {
    "new": [], 
    "old": []
  }, 
  "info": {
    "action": "config_set", 
    "callid": "5ea1c41419968", 
    "data": {
      "do_backup": true, 
      "do_reload": true, 
      "previous_config_file": "/cf/conf/backup/config-1587659796.xml"
    }, 
    "message": "ok"
  }, 
  "protonVPN": {
    "new": [], 
    "old": []
  }
}
```

**Comment by dejablue79** [comment]
For the VPN clients configured on your pfsense, do you use an IP as the `Server host or address` or the hostname?

**Comment by somedevreally** [comment]
this format: `us5173.nordvpn.com`

**Comment by dejablue79** [comment]
I guess `/get_settings` will not work as well.

Can you check if the API user you have created has permissions to read/write configurations?

I will also add an error msg if `config_get` is failing.

**Comment by somedevreally** [comment]
`/get_settings` works

```
[
  "us5173.nordvpn.com", 
  "at3360.nordvpn.com", 
  "nl606.nordvpn.com"
]
```
after i restarted the container i was able to change server `/set`

edit: these always works
```
/?q=nvpn&loc=us
/get_settings
/comp
```

**Comment by dejablue79** [comment]
ha.
ok. I will add some checks to the code

**Comment by dejablue79** [comment]
Pushed some changes.
Tell me if it helps.

**Comment by somedevreally** [comment]
got latest codeand build it, now i see new error on the docker log
```
Traceback (most recent call last):,
  File "./app.py", line 3, in <module>,
    from validators import ip_address, domain, length,
ModuleNotFoundError: No module named 'validators',

```

**Comment by dejablue79** [comment]
`validators` was added to the `requirements.txt` file as well.
can try `docker-compose up --build` if you are using Docker-Compose or `pip install validators` if you running the python code itself?

**Comment by somedevreally** [comment]
yes i did docker build, this is the error

`
vpnchanger    | Traceback (most recent call last):
vpnchanger    |   File "./app.py", line 82, in <module>
vpnchanger    |     raise Exception("Please verify \"host-address\" was entered co
rrectly")
vpnchanger    | Exception: Please verify "host-address" was entered correctly
`

**Comment by dejablue79** [comment]
ha..
what did set for `host-address`?
I'm checking for IP or domain name.

**Comment by somedevreally** [comment]
where should i set the host-address?

**Comment by somedevreally** [comment]
yes i have set the host ip of pfsense in docker composer env

**Comment by dejablue79** [comment]
Right!
Should be fixed now.

**Comment by somedevreally** [comment]
built was success, 
all links worked perfectly
```
/?q=nvpn&loc=us
/get_settings
/comp
/set
```

also does FauxAPI pkg gets uninstalled by itself? from pfsense? i had to reinstall it
when i ran `/?q=nvpn&loc=us` it was there but it vanished when i ran `/get_settings`
could be coincidence :/

**Comment by dejablue79** [comment]
Its not suppose to.
Maybe there is something in the logs?

**Comment by somedevreally** [comment]
tried setting the server, got this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app.py", line 74, in set
    return jsonify(set_servers())
  File "/usr/src/app/tasks.py", line 128, in set_servers
    server = next(iter(sorted_ndata))
StopIteration
```

**Comment by dejablue79** [comment]
Tried something else.
Can you please verify?

**Comment by somedevreally** [comment]
downloaded new code, now i get blank results
first 3 works fine
```
/?q=nvpn&loc=us
/get_settings
/comp
```
for set `/set`
```
{
  "NordVPN": {
    "new": [], 
    "old": []
  }, 
  "info": {
    "action": "config_set", 
    "callid": "5ea4450904c2a", 
    "data": {
      "do_backup": true, 
      "do_reload": true, 
      "previous_config_file": "/cf/conf/backup/config-1587823881.xml"
    }, 
    "message": "ok"
  }, 
  "protonVPN": {
    "new": [], 
    "old": []
  }
}
```

**Comment by dejablue79** [comment]
There is a chance that your NordVPNs are already set to the best one. I will change the output.
Can you verify using `/comp`?

**Comment by somedevreally** [comment]
you are right checked /comp, nordvpn is already set to best.
So in that case maybe a message? "best server already set"?

**Comment by somedevreally** [comment]
tried multiple times, i guess this is working solid now.

thanks

**Comment by somedevreally** [comment]
`nordvpn: "No Need to Update"`
looks perfect

**Comment by somedevreally** [comment]
minor UI thing, `/comp` sequence and `/set` is different.

comp
> {
  "NordVPN": {
    "bg": {
      "available_servers": {
        "7": "bg30.nordvpn.com", 
        "8": "bg31.nordvpn.com"
      }, 
      "pfsense": [
        "bg37.nordvpn.com"
      ]
    }, 
    "us": {
      "available_servers": {
        "16": "us5199.nordvpn.com", 
        "17": "us5202.nordvpn.com"
      }, 
      "pfsense": [
        "us3288.nordvpn.com", 
      ]
    }
  }

set
> "nordvpn": {
    "new": {
      "BG": [
        "bg30.nordvpn.com"
      ], 
      "US": [
        "us5199.nordvpn.com", 
      ]
    }, 
    "old": {
      "BG": [
        "bg37.nordvpn.com"
      ], 
      "US": [
        "us3288.nordvpn.com", 
      ]
    }
  },

**Comment by dejablue79** [comment]
Changed.
Thanks!
